
on:
  workflow_dispatch:
    inputs:
      f1:
        description: f1
        required: true
        default: "value"
        type: string
      f2:
        description: f2
        required: true
        default: "value"
        type: string
      fail1:
        description: fail1
        required: false
        default: false
        type: boolean
      fail2:
        description: fail2
        required: false
        default: false
        type: boolean
      run_final:
        description: set to 'final' to run final
        required: true
        default: "final"
        type: string

name: testing conditions
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs no matter what"
  job1:
    runs-on: ubuntu-latest
    if: ${{ inputs.f1 == 'value' }}
    steps:
      - run: echo "This runs when f1 is value"
      - run: exit 1
        if: ${{ inputs.fail1 }}
  job2:
    runs-on: ubuntu-latest
    if: ${{ inputs.f2 == 'value' }}
    steps:
      - run: echo "This runs when f2 is value"
      - run: exit 1
        if: ${{ inputs.fail2 }}
  final:
    if: ${{ always() && !( failure() ) && inputs.run_final == 'final' }}
    needs: [job0, job1, job2]
    runs-on: ubuntu-latest
    steps:
    - run: echo "job0 - ${{needs.job0.result}}; job1 - ${{needs.job1.result}}; job2 - ${{needs.job2.result}}"
