name: Prerelease pipeline

on:
  release:
    types:
      - prereleased
    tags:
      - 'v*'

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:

  check_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: git log -1 --format="%D" ${{ env.TAG }} |cat

  prerelease:
    runs-on: ubuntu-latest
    steps:
    - name: Create packages and upload to GH
      run: echo "Create and upload to GH binaries for ${{ env.TAG }}"

  upload_artifacts:
    if: ${{ !contains(github.event.release.tag_name, '-dev') }}
    runs-on: ubuntu-latest
    steps:
    - name: Upload artifacts
      run: echo "Artifacts for ${ {env.TAG }} uploaded"
