name: Testing reusable workflow

on:
  workflow_call:
    inputs:
      testing-value:
        description: Testing value
        required: false
        type: string
        default: ""
    secrets:
      TEST_SECRET:
        required: true

jobs:
  check_invoker_data:
    name: Check invoker data
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.server_url }}/${{ github.event.repository.full_name }}/actions/runs/${{ github.run_id }}"
      - run: echo "${{ toJson(github.event.repository) }}"
      - run: echo "${{ inputs.testing-value || 'default' }}"
      - run: echo "${{ secrets.TEST_SECRET }}"
